# 1.Getting Start
tensorflow2基础

## 1.1 tensor张量
Tensorflow中，使用张量作为数据的基本单位。Tensorflow的张量在概念上等同于多维数组，我们可以使用它来描述数学中的标量（零维数组），向量vector（一维数组），矩阵matrix（二维数组）等。

In [2]:
import tensorflow as tf 

In [5]:
# 定义一个标量（随机数）
random_float = tf.random.uniform(shape=())
#定义一个有两个元素的零向量
zero_vector = tf.zeros(shape=(2))
#定义2个2*2的常量矩阵
A = tf.constant([[1,2],[3,4]])
B = tf.constant([[5,6],[8,9]])

获取tensor相关属性

In [6]:
#查看形状
print(A.shape)
#查看数据类型
print(A.dtype)
#查看值
print(A.numpy())

(2, 2)
<dtype: 'int32'>
[[1 2]
 [3 4]]


tensor运算

In [7]:
#和
C = tf.add(A, B)
print(C.shape)
print(C.dtype)
print(C.numpy())

(2, 2)
<dtype: 'int32'>
[[ 6  8]
 [11 13]]


In [14]:
#乘积（矩阵相乘）
print(A)
print(B)
D = tf.matmul(A, B)
print(D.shape)
print(D.dtype)
print(D.numpy()) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [8 9]], shape=(2, 2), dtype=int32)
(2, 2)
<dtype: 'int32'>
[[21 24]
 [47 54]]


In [13]:
#元素对应相乘
E = tf.multiply(A,B)
print(E)

tf.Tensor(
[[ 5 12]
 [24 36]], shape=(2, 2), dtype=int32)


## 1.2 自动求导机制

e.g.1 单元函数求导数

In [16]:
x = tf.Variable(initial_value = 3.)#声明变量与其初始值
with tf.GradientTape() as tape:
    y = tf.square(x)
y_grad = tape.gradient(y, x)#计算y在x处的导数
print('y: ',y)
print('y_grad: ',y_grad)

y:  tf.Tensor(9.0, shape=(), dtype=float32)
y_grad:  tf.Tensor(6.0, shape=(), dtype=float32)


e.g.2 多元函数求偏导

In [18]:
x = tf.constant([[1., 2.],[3., 4.]])
y = tf.constant([1., 2.])
w = tf.Variable(initial_value=[[1.],[2.]])
b = tf.Variable(initial_value=1.)

with tf.GradientTape() as tape:
    L = tf.reduce_sum(tf.square(tf.matmul(x, w) + b - y))
w_grad,b_grad = tape.gradient(L,[w,b])
print('L: ',L)
print('w_grad: ',w_grad)
print('b_grad: ',b_grad)

L:  tf.Tensor(262.0, shape=(), dtype=float32)
w_grad:  tf.Tensor(
[[144.]
 [204.]], shape=(2, 1), dtype=float32)
b_grad:  tf.Tensor(60.0, shape=(), dtype=float32)


## 1.3 线性回归Linear Regression 

### Step 0. 定义数据

In [20]:
import numpy as np
year = np.array([2013,2014,2015,2016,2017],dtype=np.float32)
price = np.array([12000,14000,15000,16500,17500],dtype=np.float32)
#归一化
x = (year-year.min())/(year.max()-year.min())
y = (price-price.min())/(price.max()-price.min())
print(x)
print(y)

[0.   0.25 0.5  0.75 1.  ]
[0.         0.36363637 0.54545456 0.8181818  1.        ]


### Step 1. 初始化
y=ax+b 目标:找到合适的参数a,b的值，使得模型尽量拟合数据

In [24]:
#转换数据类型
x = tf.constant(x)
y = tf.constant(y)
#初始化参数
a = tf.Variable(initial_value=0.)
b = tf.Variable(initial_value=0.)
variables = [a,b]


### Step 2. 训练
使用梯度下降法求解

In [25]:
epochs = 10000
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
for i in range(epochs):
    with tf.GradientTape() as tape:
        y_pred = a * x + b
        loss = tf.reduce_sum(tf.square(y_pred - y))
    grads = tape.gradient(loss,variables)
    optimizer.apply_gradients(grads_and_vars=zip(grads, variables))
print(a,b)


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.9818159> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.05454662>


### Step 3. 预测

In [26]:
x_pred = 2021
pred = a * x_pred + b
print(pred)

tf.Tensor(1984.3044, shape=(), dtype=float32)
